ColorsBackground:
    Red:
        Min: 200
        Max: 255
    Blue:
        Min: 0
        Max: 200
    Green:
        Min: 50
        Max: 200
ColorsFont:
    Red:
        Min: 0
        Max: 255
    Blue:
        Min: 0
        Max: 255
    Green:
        Min: 0
        Max: 255
Line:
    Count:
        Min: 4
        Max: 12
    Size:
        Min: 2
        Max: 6
    Color:
        Red:
            Min: 0
            Max: 255
        Blue:
            Min: 0
            Max: 255
        Green:
            Min: 0
            Max: 255
Lenght: 4
Size:
    Width: 400
    Height: 100
AngleChar:
    Min: -45
    Max: 45
SizeChar:
    Min: 45
    Max: 60