ColorsBackground:
    Red:
        Min: 0
        Max: 255
    Blue:
        Min: 0
        Max: 200
    Green:
        Min: 50
        Max: 200
ColorsFont:
    Red:
        Min: 0
        Max: 255
    Blue:
        Min: 0
        Max: 255
    Green:
        Min: 0
        Max: 255
Lenght: 4
Size:
    Width: 300
    Height: 100
AngleChar:
    Min: -45
    Max: 45
SizeChar:
    Min: 50
    Max: 70